In [1]:
import pandas as pd

df = pd.read_parquet("data/raw/spy.parquet")

In [4]:
df.head()

,code,name,time_key,open,close,high,low,pe_ratio,turnover_rate,volume,turnover,change_rate,last_close
0,US.SPY,SPDR S&P 500 ETF,2023-01-03 09:41:00,429.31794,429.67564,429.71214,429.11794,0.0,0.0,284993.0,1.098415e+08,0.083318,429.31794
1,US.SPY,SPDR S&P 500 ETF,2023-01-03 09:42:00,429.65794,430.03794,430.14784,429.65794,0.0,0.0,390764.0,1.508399e+08,0.084319,429.67564
2,US.SPY,SPDR S&P 500 ETF,2023-01-03 09:43:00,430.05794,430.09294,430.35794,430.03794,0.0,0.0,335230.0,1.294856e+08,0.012790,430.03794
3,US.SPY,SPDR S&P 500 ETF,2023-01-03 09:44:00,430.10794,429.88794,430.20794,429.86794,0.0,0.0,279990.0,1.081110e+08,-0.047664,430.09294
4,US.SPY,SPDR S&P 500 ETF,2023-01-03 09:45:00,429.88794,429.20794,430.03794,429.09344,0.0,0.0,338855.0,1.306818e+08,-0.158181,429.88794

In [24]:
df['datetime'] = pd.to_datetime(df['time_key'])
df = df[df["datetime"] >= "2023-01-04 09:45:00"]

In [25]:
df.head(20)

,code,name,time_key,open,close,high,low,pe_ratio,turnover_rate,volume,turnover,change_rate,last_close,datetime
394,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:45:00,427.40794,426.54784,427.42794,426.36794,0.0,0.0,347283.0,1.329619e+08,-0.203571,427.41794,2023-01-04 09:45:00
395,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:46:00,426.52794,426.50794,426.75594,426.46794,0.0,0.0,262990.0,1.006494e+08,-0.009354,426.54784,2023-01-04 09:46:00
396,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:47:00,426.49794,426.60794,426.64794,426.08854,0.0,0.0,285423.0,1.091831e+08,0.023446,426.50794,2023-01-04 09:47:00
397,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:48:00,426.59794,426.75794,426.82794,426.58794,0.0,0.0,144891.0,5.546313e+07,0.035161,426.60794,2023-01-04 09:48:00
398,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:49:00,426.75794,426.75794,426.93814,426.52794,0.0,0.0,122622.0,4.693579e+07,0.000000,426.75794,2023-01-04 09:49:00
399,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:50:00,426.78794,426.63784,426.79794,426.34794,0.0,0.0,151208.0,5.786013e+07,-0.028142,426.75794,2023-01-04 09:50:00
400,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:51:00,426.63794,426.84794,427.07294,426.60794,0.0,0.0,271123.0,1.038365e+08,0.049246,426.63784,2023-01-04 09:51:00
401,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:52:00,426.85794,426.57794,426.95794,426.48794,0.0,0.0,169237.0,6.478414e+07,-0.063254,426.84794,2023-01-04 09:52:00
402,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:53:00,426.56794,426.62794,426.76794,426.37794,0.0,0.0,209534.0,8.017882e+07,0.011721,426.57794,2023-01-04 09:53:00
403,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:54:00,426.62794,426.74794,426.77784,426.44794,0.0,0.0,109623.0,4.195075e+07,0.028128,426.62794,2023-01-04 09:54:00
404,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:55:00,426.69794,426.78794,426.88794,426.60794,0.0,0.0,75658.0,2.896487e+07,0.009373,426.74794,2023-01-04 09:55:00
405,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:56:00,426.76794,426.94794,427.05794,426.76794,0.0,0.0,214258.0,8.205958e+07,0.037489,426.78794,2023-01-04 09:56:00
406,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:57:00,426.95794,426.78094,426.95794,426.53794,0.0,0.0,124430.0,4.763132e+07,-0.039115,426.94794,2023-01-04 09:57:00
407,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:58:00,426.81794,426.82804,427.01794,426.78794,0.0,0.0,86417.0,3.309480e+07,0.011036,426.78094,2023-01-04 09:58:00
408,US.SPY,SPDR S&P 500 ETF,2023-01-04 09:59:00,426.83794,426.98294,427.03784,426.68794,0.0,0.0,92073.0,3.525491e+07,0.036291,426.82804,2023-01-04 09:59:00
409,US.SPY,SPDR S&P 500 ETF,2023-01-04 10:00:00,426.98794,427.15794,427.21794,426.86794,0.0,0.0,127767.0,4.895116e+07,0.040985,426.98294,2023-01-04 10:00:00
410,US.SPY,SPDR S&P 500 ETF,2023-01-04 10:01:00,427.08794,426.18794,427.12794,425.49794,0.0,0.0,882509.0,3.373280e+08,-0.227082,427.15794,2023-01-04 10:01:00
411,US.SPY,SPDR S&P 500 ETF,2023-01-04 10:02:00,426.13794,426.70794,426.91394,426.13784,0.0,0.0,369537.0,1.414003e+08,0.122012,426.18794,2023-01-04 10:02:00
412,US.SPY,SPDR S&P 500 ETF,2023-01-04 10:03:00,426.70794,427.44794,428.19794,426.70794,0.0,0.0,808892.0,3.103763e+08,0.173421,426.70794,2023-01-04 10:03:00
413,US.SPY,SPDR S&P 500 ETF,2023-01-04 10:04:00,427.44294,426.55794,427.44794,426.21794,0.0,0.0,369741.0,1.415726e+08,-0.208212,427.44794,2023-01-04 10:04:00

In [ ]:
n = (20,401,10)
params_signal = {
    
    'zscore': np.arange(-3, 3.1, 0.1),
    'minmax': np.arange(-1, 1.1, 0.1),
    'xxx'.....
    ...
    ...
    ...
}